language: python
cache: pip
sudo: false
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coveralls
env:
  matrix:
  - APP_CONFIG_FILE=testing
  global:
    secure: KeSjV6DU+TyWqcVZ9is95WatvLZz03s8ZD1UYeQjgUzCXQvOykUbZLoErrM/Cn6eoMNZjrddGQ65OdVap9JMa7cADDXg47C89IkfjJHGkTrXmhdYB3/stAkbYjpS9GHC4oEPLllM/i/FPQtiZFVej9qSRzpjBcT5/P+BO0LC+nQ=
script: python manage.py tests
after_success:
- coveralls
- if [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_BRANCH" == production ]];
  then
- openssl aes-256-cbc -k '$DEPLOY_KEY' -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa
- git remote add dokku dokku@dartplan.com:dartplan
- git push dokku production
- fi
deploy:
  provider: heroku
  api_key:
    secure: p9YZXHHWrvcRVKyO7RztsnTLylzqzyirDw9dlVO0xVBcBJuOniz4+zaiKK1f3UQGkzxT1BmRIdp89AJPDYlqTLdgRCbehQ4zKS/kC8NQt81N6uA1tctZnCD4byjEpoXjkZoGMl8mL/sGLTZy6CdGXPwLnQDA9nD0YMrobsAfZ4M=
  app:
    master: dartplan-staging
  run:
  - python manage.py db upgrade
