language: python
cache: pip
sudo: false
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_b5a7b01d0cd0_key -iv $encrypted_b5a7b01d0cd0_iv
  -in travis.pub.enc -out ~\/.ssh/travis.pub -d
install:
- pip install -r requirements.txt
- pip install coveralls
env:
- APP_CONFIG_FILE=testing
script: python manage.py tests
after_success:
- coveralls
- if [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_BRANCH" == production ]];
  then
- chmod 600 .ssh/travis.pub
- ssh-add .ssh/travis.pub
- git remote add dokku dokku@dartplan.com:dartplan
- git push dokku production
- fi
deploy:
  provider: heroku
  api_key:
    secure: p9YZXHHWrvcRVKyO7RztsnTLylzqzyirDw9dlVO0xVBcBJuOniz4+zaiKK1f3UQGkzxT1BmRIdp89AJPDYlqTLdgRCbehQ4zKS/kC8NQt81N6uA1tctZnCD4byjEpoXjkZoGMl8mL/sGLTZy6CdGXPwLnQDA9nD0YMrobsAfZ4M=
  app:
    master: dartplan-staging
  run:
  - python manage.py db upgrade
