from fixtures.app_fixtures import *
from fixtures.user_fixtures import *
from fixtures.plan_fixtures import *
from fixtures.term_fixtures import *
from fixtures.course_fixtures import *
from fixtures.offering_fixtures import *
from fixtures.department_fixtures import *
from fixtures.distrib_fixtures import *
from fixtures.hour_fixtures import *
