"""empty message

Revision ID: 23817faaccb9
Revises: None
Create Date: 2015-04-27 12:32:26.175374

"""

# revision identifiers, used by Alembic.
revision = '23817faaccb9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hour_period'), 'hour', ['period'], unique=True)

    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('abbr', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_abbr'), 'department', ['abbr'], unique=True)
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('netid', sa.String(length=15), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('grad_year', sa.SmallInteger(), nullable=True),
    sa.Column('email_course_updates', sa.Boolean(), nullable=True),
    sa.Column('email_Dartplan_updates', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_netid'), 'user', ['netid'], unique=True)

    op.create_table('distributive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbr', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributive_abbr'), 'distributive', ['abbr'], unique=True)

    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('season', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('avg_median', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_name'), 'course', ['name'], unique=False)

    op.create_table('user_terms',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('offering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('hour_id', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Unicode(length=25000), nullable=True),
    sa.Column('median', sa.String(length=5), nullable=True),
    sa.Column('added', sa.String(length=2), nullable=True),
    sa.Column('user_added', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['hour_id'], ['hour.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offering_distribs',
    sa.Column('offering_id', sa.Integer(), nullable=True),
    sa.Column('distributive_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['distributive_id'], ['distributive.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], )
    )
    op.create_table('user_course',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('offering_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_course')
    op.drop_table('offering_distribs')
    op.drop_table('offering')
    op.drop_table('user_terms')
    op.drop_index(op.f('ix_course_name'), 'course')

    op.drop_table('course')
    op.drop_table('term')
    op.drop_index(op.f('ix_distributive_abbr'), 'distributive')

    op.drop_table('distributive')
    op.drop_index(op.f('ix_user_netid'), 'user')

    op.drop_table('user')
    op.drop_index(op.f('ix_department_name'), 'department')
    op.drop_index(op.f('ix_department_abbr'), 'department')

    op.drop_table('department')
    op.drop_index(op.f('ix_hour_period'), 'hour')

    op.drop_table('hour')
    ### end Alembic commands ###
