"""empty message

Revision ID: 3150b02dca1f
Revises: f4b6d22c97a7
Create Date: 2016-06-26 02:11:29.496180

"""

# revision identifiers, used by Alembic.
revision = '3150b02dca1f'
down_revision = 'f4b6d22c97a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_plan_default'), ['default'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_default'))
        batch_op.drop_column('default')

    ### end Alembic commands ###
