"""empty message

Revision ID: 39306d04feb7
Revises: 4bf518399c05
Create Date: 2016-04-02 23:23:25.009001

"""

# revision identifiers, used by Alembic.
revision = '39306d04feb7'
down_revision = '4bf518399c05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_course')
    op.drop_table('user_terms')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_terms',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('term_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], [u'term.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], )
    )
    op.create_table('user_course',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('offering_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], [u'offering.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], )
    )
    ### end Alembic commands ###
