"""empty message

Revision ID: 4bf518399c05
Revises: 23817faaccb9
Create Date: 2016-04-01 02:27:50.459922

"""

# revision identifiers, used by Alembic.
revision = '4bf518399c05'
down_revision = '23817faaccb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_terms',
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], )
    )
    op.create_table('plan_offerings',
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('offering_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_offerings')
    op.drop_table('plan_terms')
    op.drop_table('plan')
    ### end Alembic commands ###
